name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Xcode 12.4
        run: |
          sudo xcode-select -switch /Applications/Xcode_12.4.app

      - name: Lint
        run: swiftlint 
   
