name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-15
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: iOS
            sdk: iphonesimulator
            destination: 'platform=iOS Simulator,name=iPhone 16,OS=latest'
            download-runtime: iOS
          - platform: macOS
            sdk: macosx
            destination: 'platform=macOS'
            download-runtime: ''
          - platform: tvOS
            sdk: appletvsimulator
            destination: 'platform=tvOS Simulator,name=Apple TV,OS=latest'
            download-runtime: tvOS
    name: test (${{ matrix.platform }})
    steps:
      - name: Checkout 
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2

      - name: Set Xcode 16.3
        run: |
          sudo xcode-select -switch /Applications/Xcode_16.3.app
          xcodebuild -runFirstLaunch

      - name: Install Simulator Runtime
        if: matrix.download-runtime != ''
        run: |
          xcrun simctl list > /dev/null
          sudo xcodebuild -downloadPlatform ${{ matrix.download-runtime }}

      - name: Carthage Bootstrap
        run: carthage bootstrap --use-xcframeworks
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          xcodebuild test \
            -project Experiment.xcodeproj \
            -scheme Experiment \
            -sdk ${{ matrix.sdk }} \
            -destination '${{ matrix.destination }}'
